version: '3'
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: njlwsnurgjndny
      POSTGRES_PASSWORD: 46cd51b304900304f4c6eb6b51198441cc9edf19158d66301cd5660f995a8cea
      POSTGRES_HOST: jdbc:postgresql://ec2-34-242-154-118.eu-west-1.compute.amazonaws.com/ddg2l7rs2uqffc
  app0:
    build: .
    image: "server-app.jar"
    ports:
      - "8761:8761"
  app1:
    build: .
    image: "email-conformation.jar"
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ec2-34-242-154-118.eu-west-1.compute.amazonaws.com/ddg2l7rs2uqffc
      SPRING_DATASOURCE_USERNAME: njlwsnurgjndny
      SPRING_DATASOURCE_PASSWORD: 46cd51b304900304f4c6eb6b51198441cc9edf19158d66301cd5660f995a8cea
    depends_on:
      - db
      - app0
      - app5
  app2:
    build: .
    image: "reviews-app.jar"
    ports:
      - "9002:9002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ec2-34-242-154-118.eu-west-1.compute.amazonaws.com/ddg2l7rs2uqffc
      SPRING_DATASOURCE_USERNAME: njlwsnurgjndny
      SPRING_DATASOURCE_PASSWORD: 46cd51b304900304f4c6eb6b51198441cc9edf19158d66301cd5660f995a8cea
    depends_on:
      - db
      - app0
      - app5
  app3:
    build: .
    image: "user-app.jar"
    ports:
      - "9003:9003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ec2-34-242-154-118.eu-west-1.compute.amazonaws.com/ddg2l7rs2uqffc
      SPRING_DATASOURCE_USERNAME: njlwsnurgjndny
      SPRING_DATASOURCE_PASSWORD: 46cd51b304900304f4c6eb6b51198441cc9edf19158d66301cd5660f995a8cea
    depends_on:
      - db
      - app0
      - app5
  app4:
    build: .
    image: "web-app.jar"
    ports:
      - "9004:9004"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ec2-34-242-154-118.eu-west-1.compute.amazonaws.com/ddg2l7rs2uqffc
      SPRING_DATASOURCE_USERNAME: njlwsnurgjndny
      SPRING_DATASOURCE_PASSWORD: 46cd51b304900304f4c6eb6b51198441cc9edf19158d66301cd5660f995a8cea
    depends_on:
      - db
      - app0
      - app5
  app5:
    build: .
    image: "api-gate.jar"
    ports:
      - "9191:9191"
    depends_on:
      - app0